// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtyqomvadilrczghvxtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0eXFvbXZhZGlscmN6Z2h2eHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzM2MjUsImV4cCI6MjA2NDYwOTYyNX0.hNHhYRkAJSaWIZxkqofzqEgp9qAJGbLk6FciLf82A9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);